import { Task } from '../models/task';
import { v4 as uuidv4 } from 'uuid';

const priorities: Task['priority'][] = ['Low', 'Medium', 'High'];
const statuses: Task['status'][] = ['pending', 'completed'];

const seedTitles: string[] = [
  'Set up project repository',
  'Define initial requirements',
  'Design database schema',
  'Configure CI/CD pipeline',
  'Write API specification',
  'Implement user authentication',
  'Build task creation endpoint',
  'Build task listing endpoint',
  'Build task update endpoint',
  'Build task delete endpoint',
  'Add input validation to API',
  'Write unit tests for taskService',
  'Write integration tests for routes',
  'Set up ESLint and Prettier',
  'Configure TypeScript strict mode',
  'Create React project scaffold',
  'Build TaskItem component',
  'Build TaskList component',
  'Build TaskForm component',
  'Wire TaskForm to POST /tasks',
  'Wire TaskList to GET /tasks',
  'Add loading state to TaskList',
  'Add error state to TaskList',
  'Add empty state to TaskList',
  'Extract useTasks custom hook',
  'Extract taskApiService module',
  'Add priority badge styles',
  'Add status indicator styles',
  'Make UI responsive for mobile',
  'Add Refresh button to TasksPage',
  'Implement task filtering by status',
  'Implement task filtering by priority',
  'Add sort by creation date',
  'Add sort by priority',
  'Persist tasks to local storage',
  'Load tasks from local storage on startup',
  'Clear completed tasks feature',
  'Mark all tasks as complete feature',
  'Add task count summary header',
  'Write JSDoc for taskService',
  'Write JSDoc for taskApiService',
  'Write JSDoc for useTasks hook',
  'Document API endpoints in README',
  'Fix CORS configuration on API',
  'Add rate limiting middleware',
  'Set up environment variables',
  'Add health check endpoint',
  'Review and refactor TaskItem',
  'Review and refactor TaskList',
  'Review and refactor TasksPage',
  'Validate TypeScript across client',
  'Validate TypeScript across server',
  'Fix moduleResolution for Vite config',
  'Split tsconfig for client and server',
  'Add Vite proxy config for API',
  'Create custom agent for Task App',
  'Create ui-review-skill',
  'Create task-ui prompt file',
  'Review separation of concerns in components',
  'Extract TaskListLoading component',
  'Extract TaskListError component',
  'Extract TaskListEmpty component',
  'Rename tick to refreshKey in useTasks',
  'Add CSS import to sub-components',
  'Add btn class to Retry button',
  'Extract isCompleted const in TaskItem',
  'Add seed data for demo purposes',
  'Verify 100 tasks load on startup',
  'Test POST /tasks with new seed data',
  'Test GET /tasks returns all seeded tasks',
  'Review priority distribution in seed data',
  'Review status distribution in seed data',
  'Add createdAt timestamps to seed tasks',
  'Confirm seed data matches Task model',
  'Review task titles for clarity',
  'Write end-to-end test for task flow',
  'Add task detail view page',
  'Add task edit modal',
  'Add delete confirmation dialog',
  'Improve error messages in API',
  'Improve empty-state copy in UI',
  'Add keyboard navigation support',
  'Improve accessibility with ARIA labels',
  'Add page title and meta tags',
  'Review and update copilot instructions',
  'Update project README',
  'Tag first stable release',
  'Plan next sprint backlog',
  'Retrospective on Copilot-assisted dev',
  'Demo application to stakeholders',
  'Collect feedback from demo',
  'Prioritise feedback into backlog',
  'Refine task filtering UX',
  'Add pagination to task list',
  'Explore real database integration',
  'Research authentication options',
  'Evaluate cloud deployment targets',
  'Document lessons learned',
  'Archive completed sprint tasks',
  'Close resolved GitHub issues',
];

function seedDate(offsetDays: number): string {
  const d = new Date('2026-03-01T08:00:00.000Z');
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString();
}

export const seedTasks: Task[] = seedTitles.map((title, i) => ({
  id: uuidv4(),
  title,
  priority: priorities[i % priorities.length],
  status: statuses[i % 4 === 0 ? 1 : 0], // every 4th task is completed
  createdAt: seedDate(i),
}));
